# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alterarestoque.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterarEstoque(object):
    def setupUi(self, AlterarEstoque):
        AlterarEstoque.setObjectName("AlterarEstoque")
        AlterarEstoque.resize(181, 134)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        AlterarEstoque.setFont(font)
        AlterarEstoque.setStyleSheet("")
        self.label_54 = QtWidgets.QLabel(AlterarEstoque)
        self.label_54.setGeometry(QtCore.QRect(20, 20, 131, 22))
        self.label_54.setObjectName("label_54")
        self.codigo = QtWidgets.QLineEdit(AlterarEstoque)
        self.codigo.setGeometry(QtCore.QRect(30, 50, 119, 20))
        self.codigo.setObjectName("codigo")
        self.alterar = QtWidgets.QPushButton(AlterarEstoque)
        self.alterar.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.alterar.setObjectName("alterar")
        self.cancelar = QtWidgets.QPushButton(AlterarEstoque)
        self.cancelar.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.cancelar.setObjectName("cancelar")

        self.retranslateUi(AlterarEstoque)
        QtCore.QMetaObject.connectSlotsByName(AlterarEstoque)

    def retranslateUi(self, AlterarEstoque):
        _translate = QtCore.QCoreApplication.translate
        AlterarEstoque.setWindowTitle(_translate("AlterarEstoque", "Dialog"))
        self.label_54.setText(_translate("AlterarEstoque", "Digite a Quantidade!!!"))
        self.alterar.setText(_translate("AlterarEstoque", "Alterar"))
        self.cancelar.setText(_translate("AlterarEstoque", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlterarEstoque = QtWidgets.QDialog()
    ui = Ui_AlterarEstoque()
    ui.setupUi(AlterarEstoque)
    AlterarEstoque.show()
    sys.exit(app.exec_())
